const ERROR_CODES = {
  INVALID_JSON: 'INVALID_JSON',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMAIL_AND_USERNAME_EXIST: 'EMAIL_AND_USERNAME_EXIST',
  AVAILABILITY_WINDOW_NOT_FOUND: 'AVAILABILITY_WINDOW_NOT_FOUND',
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INVALID_AUTHORIZATION_HEADER: 'INVALID_AUTHORIZATION_HEADER',
  REGISTRATION_CONFLICT: 'REGISTRATION_CONFLICT',
  UPDATE_FIELD_CONFLICT: 'UPDATE_FIELD_CONFLICT',
  TOO_MANY_AUTH_ATTEMPTS: 'TOO_MANY_AUTH_ATTEMPTS',
};
// enum-like style for common error codes

Object.freeze(ERROR_CODES);

export default ERROR_CODES;

// used to avoid hard coding the error codes.
// this way I can avoid inconsistent error codes, and accidental miss spelling
// The error codes are in an object to make it cleaner and more centralized so that I dont have to export multiple variables.
// This object is for error codes that are used multiple times, not one time use error codes
