const ERROR_CODES = {
  // ---------------------------------------------------------------------------
  // Auth
  // ---------------------------------------------------------------------------
  INVALID_TOKEN: 'INVALID_TOKEN',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INVALID_AUTHORIZATION_HEADER: 'INVALID_AUTHORIZATION_HEADER',
  REGISTRATION_CONFLICT: 'REGISTRATION_CONFLICT',
  TOO_MANY_AUTH_ATTEMPTS: 'TOO_MANY_AUTH_ATTEMPTS',
  AUTH_USER_DELETED_DURING_REQUEST: 'AUTH_USER_DELETED_DURING_REQUEST',

  // ---------------------------------------------------------------------------
  // Users
  // ---------------------------------------------------------------------------
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMAIL_AND_USERNAME_EXIST: 'EMAIL_AND_USERNAME_EXIST',
  UPDATE_FIELD_CONFLICT: 'UPDATE_FIELD_CONFLICT',
  DELETED_USER_CANNOT_RESERVE: 'DELETED_USER_CANNOT_RESERVE',

  // ---------------------------------------------------------------------------
  // Resources
  // ---------------------------------------------------------------------------
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_DELETED: 'RESOURCE_DELETED',
  RESOURCE_INACTIVE: 'RESOURCE_INACTIVE',
  RESOURCE_STATE_CHANGED: 'RESOURCE_STATE_CHANGED',
  RESOURCE_ALREADY_ACTIVE: 'RESOURCE_ALREADY_ACTIVE',
  RESOURCE_NAME_ALREADY_EXISTS_FOR_OWNER:
    'RESOURCE_NAME_ALREADY_EXISTS_FOR_OWNER',
  RESOURCE_OWNER_NOT_FOUND: 'RESOURCE_OWNER_NOT_FOUND',
  RESOURCE_NAME_HAS_MULTIPLE_SPACES: 'RESOURCE_NAME_HAS_MULTIPLE_SPACES',
  CANNOT_ACTIVATE_DELETED_RESOURCE: 'CANNOT_ACTIVATE_DELETED_RESOURCE',

  // ---------------------------------------------------------------------------
  // Availability Windows
  // ---------------------------------------------------------------------------
  AVAILABILITY_WINDOW_NOT_FOUND: 'AVAILABILITY_WINDOW_NOT_FOUND',
  NOT_A_FUTURE_AVAILABILITY_WINDOW: 'NOT_A_FUTURE_AVAILABILITY_WINDOW',
  AVAILABILITY_WINDOW_STATE_CHANGED: 'AVAILABILITY_WINDOW_STATE_CHANGED',
  WINDOW_END_TIME_NOT_AFTER_START_TIME: 'WINDOW_END_TIME_NOT_AFTER_START_TIME',
  AVAILABILITY_WINDOW_EXPIRED: 'AVAILABILITY_WINDOW_EXPIRED',
  AVAILABILITY_WINDOW_DELETED: 'AVAILABILITY_WINDOW_DELETED',
  WINDOW_ALREADY_EXISTS: 'WINDOW_ALREADY_EXISTS',
  WINDOW_OVERLAP_OR_ADJACENCY: 'WINDOW_OVERLAP_OR_ADJACENCY',
  WINDOW_RESOURCE_NOT_FOUND: 'WINDOW_RESOURCE_NOT_FOUND',
  WINDOW_INVALID_HALF_HOUR_BOUNDARY: 'WINDOW_INVALID_HALF_HOUR_BOUNDARY',

  // ---------------------------------------------------------------------------
  // Allowed Durations
  // ---------------------------------------------------------------------------
  ALLOWED_DURATION_NOT_FOUND: 'ALLOWED_DURATION_NOT_FOUND',
  ALLOWED_DURATION_LONGER_THAN_WINDOW: 'ALLOWED_DURATION_LONGER_THAN_WINDOW',
  ALLOWED_DURATION_STATE_CHANGED: 'ALLOWED_DURATION_STATE_CHANGED',
  ALLOWED_DURATION_ALREADY_EXISTS: 'ALLOWED_DURATION_ALREADY_EXISTS',
  DURATION_WINDOW_NOT_FOUND: 'DURATION_WINDOW_NOT_FOUND',
  DURATION_WINDOW_DELETED: 'DURATION_WINDOW_DELETED',
  TOO_MANY_ALLOWED_DURATIONS: 'TOO_MANY_ALLOWED_DURATIONS',
  CANNOT_DELETE_LAST_ALLOWED_DURATION: 'CANNOT_DELETE_LAST_ALLOWED_DURATION',

  // ---------------------------------------------------------------------------
  // Reservations
  // ---------------------------------------------------------------------------
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  RESERVATION_OVERLAP: 'RESERVATION_OVERLAP',
  RESERVATION_WINDOW_RESOURCE_MISMATCH: 'RESERVATION_WINDOW_RESOURCE_MISMATCH',
  RESERVATION_INVALID_QUARTER_HOUR_BOUNDARY:
    'RESERVATION_INVALID_QUARTER_HOUR_BOUNDARY',
  RESERVATION_END_TIME_GREATER_THAN_START_TIME:
    'RESERVATION_END_TIME_GREATER_THAN_START_TIME',
  RESERVATION_COMPLETION_IRREVERSIBLE: 'RESERVATION_COMPLETION_IRREVERSIBLE',
  RESERVATION_RESOURCE_DELETED: 'RESERVATION_RESOURCE_DELETED',
  RESERVATION_RESOURCE_INACTIVE: 'RESERVATION_RESOURCE_INACTIVE',
  RESERVATION_OUTSIDE_AVAILABILITY_WINDOW:
    'RESERVATION_OUTSIDE_AVAILABILITY_WINDOW',
  RESERVATION_DURATION_NOT_ALLOWED: 'RESERVATION_DURATION_NOT_ALLOWED',
  RESERVATION_PARTY_SIZE_EXCEEDS_CAPACITY:
    'RESERVATION_PARTY_SIZE_EXCEEDS_CAPACITY',
  RESERVATION_ALREADY_STARTED: 'RESERVATION_ALREADY_STARTED',
  RESERVATION_STATE_CHANGED: 'RESERVATION_STATE_CHANGED',
  RESERVATION_ALREADY_CANCELLED: 'RESERVATION_ALREADY_CANCELLED',
  RESERVATION_ALREADY_COMPLETED: 'RESERVATION_ALREADY_COMPLETED',
  RESERVATION_ALREADY_ENDED: 'RESERVATION_ALREADY_ENDED',
  RESERVATION_NO_LONGER_CANCELLABLE: 'RESERVATION_NO_LONGER_CANCELLABLE',
  RESERVATION_CANCELLATION_NOTICE_PASSED:
    'RESERVATION_CANCELLATION_NOTICE_PASSED',
  RESERVATION_NOT_STARTED: 'RESERVATION_NOT_STARTED',

  // ---------------------------------------------------------------------------
  // Database Fallbacks
  // ---------------------------------------------------------------------------
  DB_UNIQUE_CONSTRAINT_VIOLATION: 'DB_UNIQUE_CONSTRAINT_VIOLATION',
  DB_EXCLUSION_CONSTRAINT_VIOLATION: 'DB_EXCLUSION_CONSTRAINT_VIOLATION',
  DB_FOREIGN_KEY_VIOLATION: 'DB_FOREIGN_KEY_VIOLATION',
  DB_CHECK_CONSTRAINT_VIOLATION: 'DB_CHECK_CONSTRAINT_VIOLATION',
  DB_NOT_NULL_VIOLATION: 'DB_NOT_NULL_VIOLATION',
  DB_TRIGGER_REJECTED_OPERATION: 'DB_TRIGGER_REJECTED_OPERATION',

  // ---------------------------------------------------------------------------
  // Miscellaneous
  // ---------------------------------------------------------------------------
  INVALID_JSON: 'INVALID_JSON',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

Object.freeze(ERROR_CODES);

export default ERROR_CODES;
